# CODE COURSE - Tutorial Linear algebra.
---

 This tutorial will explain in a interactive way the tools you need to be able to start with PCA and clustering. This tutorial is specified on the tools you need of linear algebra. 

## Contents of the tutorial
1. Vector and matrix operations
    * Basics
    * Vector addition 
    * Vector scalar multiplication
    * Matrix summation
    * Matrix multiplication
    * Transpose matrix 
    * Query matrix index
    * Exercises
2. Eigenvecotoren & eigenvalues
    * Definitions 
    * The calculation of eigenvalues and eigenvectoren in python
    * Exercises
3. Transformation  
4. Innerproduct, length and orthogonality 
5. Covariance matrix 



<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-bottom:-20px"></div>

### 1. Vector and matrix operations

<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-top:5px;"></div>

#### 1.2 Basics

Vector and matric operations are important due to you need them by the calculations of the eigenvectors, eigenvalues and transformations. <br/>
Firstly, you have to import Numpy. Numpy is a Python pakket which makes it easy to use matrices. <br>
If you want to learn more about the Python package Numpy you can use this link. https://www.w3resource.com/python-exercises/numpy/index.php




In [3]:
 import numpy as np

Secondly, you have to know how you make a matrix in python. You can do this with **np.array()**.With the function print(a) you can see the matrix you made.

In [34]:
A = np.array([[1.1, 2, 3], [3, 4, 5]])
print('This is matrix A.')
print(A) 

This is matrix A.
[[ 1.1  2.   3. ]
 [ 3.   4.   5. ]]


You can also use the following code; **np.mat()**

In [37]:
B = np.mat("1.1 2 3;3 4 5")
print('This is matrix B.')
print(B) 

This is matrix B.
[[ 1.1  2.   3. ]
 [ 3.   4.   5. ]]


Matrices could be in integers, floats and complex numbers. Same examples are given below.

In [36]:
C = np.array([[1, 2, 3], [3, 4, 5]])
print('This is matrix C.')
print(C) 
D = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print('This is matrix D.')
print(D) 
E = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print('This is matrix E.')
print(E)

This is matrix C.
[[1 2 3]
 [3 4 5]]
This is matrix D.
[[ 1.1  2.   3. ]
 [ 3.   4.   5. ]]
This is matrix E.
[[ 1.+0.j  2.+0.j  3.+0.j]
 [ 3.+0.j  4.+0.j  5.+0.j]]


In [53]:
from IPython.display import display, Math, Latex


#### 1.2 Vector addition
This is a very simple operation which you have learn during the linear algebra courses. You make a vector the same way as you make a matrix. The only difference is that you have only one row.

In [39]:
A = np.array([2, 4])
B = np.array([9, -3])
C = A + B  
print('This is vector C.')
print(C)

This is matrix C.
[11  1]


#### 1.3 Vector scalar multiplication
It is also possible to multiply the vector with a scalar. You have to use the following code


In [41]:
A = np.array([2, 4])
B = 4*A
print('This is vector B.')
print(B)


This is vector B.
[ 8 16]


#### 1.4 Matrix summation 
Now you know how do operations with vectors, we could make the step to matrices. You could also sum matrices with eachother.

In [58]:
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B  
print(C)

[[11  1]
 [ 8  0]]


#### 1.5 Matrix multiplication
If A is an m×n matrix, and if B is an n×p matrix with columns b<sub>1</sub>, . . . , b<sub>p</sub>, <br/>
then the product AB is the m×p matrix whose columns are A<sub>b1</sub>, . . . , A<sub>bp</sub>. <br/>
You have to use **.dot()** to multiply two or more matrixes with eachother

In [56]:
A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
AB = A.dot(B)
print(AB)

[[ 36 -12]
 [ -1   2]]


In [18]:
from numpy.linalg import multi_dot
A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1, 1], [2, 1, 1], [3, -3, 1]])
C = np.array([[1, 2., 1], [2, 1, 1], [3, -3, 1]])
ABC = multi_dot([A, B, C])
#AB = B.dot(C)
#ABC= AB.dot(A)
ABC2 =  A.dot(B).dot(C)
print(A)
print(ABC2)

[[ 3  6  7]
 [ 5 -3  0]]
[[ 60.  12.  40.]
 [  9.  -6.   3.]]


#### 1.6 Transpose matrix 
Given an m×n matrix A, the transpose of A is the n×m matrix, denoted by A<sup>T</sup> ,
whose columns are formed from the corresponding rows of A. <br/> 
The transpose matrix could be calculated with the use of **.transpose()**.
```python
    A = np.array([[1, 1], [2, 1], [3, -3]])
    print(A.transpose())
```



#### 1.7 Query matrix index
With index it is possible to select specific indices out of the matrix. 


In [60]:
A = np.array([[1, 4, 5, 12],
            [-5, 8, 9, 0],
            [-6, 7, 11, 19]])
print("A[1][2] =", A[1][2]) # Third element
print("A[0] =", A[0]) # First Row
    
column = [];        # empty list
for row in A:
    column.append(row[2])   
print("3rd column =", column) # the thrid column

A[1][2] = 9
A[0] = [ 1  4  5 12]
3rd column = [5, 9, 11]


#### 1.8 Exercises

**1.8.1** Calculate the sum of the following vectors: <br>
$ A = \left[ \begin{array}{ccc} 11\\ 1\end{array} \right]$,
$ B = \left[ \begin{array}{ccc} -8\\ 10\end{array} \right]$, 
$ C = \left[ \begin{array}{ccc} 11.1\\ 1\end{array} \right]$ 




In [ ]:
#code.....

**1.8.2** Perform a vector-matrix multiplication with the following vector $ A = \left[ \begin{array}{ccc} 6\\ 1\end{array} \right]$ and matrix $ B = \left[ \begin{array}{ccc} -8 & 10 & 11\\ 8 & 10 & 56\end{array} \right]$. 

In [ ]:
#code....

**1.8.3** Calculate the multiplication of the following three matrices; <br>
$ A = \left[ \begin{array}{ccc} -8 & 10 & 11\\ 8 & 10 & 56\end{array} \right]$ <br> <br>
$ B = \left[ \begin{array}{ccc} -7 & 17 & 3\\ 5 & 10 & 5\end{array} \right]$ <br> <br>
$ C = \left[ \begin{array}{ccc} -9 & 3 & 11\\ 17 & 11 & 6\end{array} \right]$ <br> <br>

In [ ]:
#code....

**1.8.4** Given is a matrix $ A = \left[ \begin{array}{ccc} 2 & 3 & 11\\ 4 & 5 & 56 \\ 6 & 7 & 45 \end{array} \right]$. Calculate the transpose of this reduced matrix. Secondly, select the second row of the matrix.


In [59]:
#code....

<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-bottom:-20px"></div>

### 2.  Eigenvalues & Eigenvectoren

<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-top:5px;"></div>

#### 2.1 Definitions

It is important to understand the terms eigenvalue and eigenvector, because they are the basis of PCA.<br>
An eigenvector of a matrix A<sub>mxn</sub> is a **nonzero** vecotr x such that: 
### A$\bullet$X = $\lambda$X 
for some scalar $\lambda$ <br>
A scalar $\lambda$ is called an eigenvalues of A if there is **nontrival** solution x of **A$\bullet$X = $\lambda$X**; such an eigenvector corresponding to $\lambda$
<br><br>
It is easy to determine if a given vector is an eigenvector of a matrix. <br> 
**Example 1** <br>
let $ A = \left[ \begin{array}{ccc} 1 & 6\\ 5 & 2 \end{array} \right]$, $ u = \left[ \begin{array}{ccc} 6\\ -5 \end{array} \right]$ and  $ v = \left[ \begin{array}{ccc} 3\\ -2 \end{array} \right]$. Are u and v eigenvectoren of A?<br>
**Calculation**<br>
    Au = $\left[ \begin{array}{ccc} 1 & 6\\ 5 & 2 \end{array} \right]$ $\left[ \begin{array}{ccc} 6\\ -5 \end{array} \right]$ = $\left[ \begin{array}{ccc} -24\\ 20 \end{array} \right]$ = $-4$$\left[ \begin{array}{ccc} 6\\ -5 \end{array} \right]$ = $-4u$ <br>
    Av = $\left[ \begin{array}{ccc} 1 & 6\\ 5 & 2 \end{array} \right]$ $\left[ \begin{array}{ccc} 3\\ -2 \end{array} \right]$ = $\left[ \begin{array}{ccc} -9\\ 11 \end{array} \right]$ $\neq$ $\lambda$ $\left[ \begin{array}{ccc} 3\\ -2 \end{array} \right]$ = $-4u$

Thus u is an eigenvector corresponding to an eigenvalue (-4), but v is not an eigenvector of A, <br> 
because Av is not a multiple of v. <br> 

It is also easy to decide if a specified scalar is an eigenvalue. <br>
**Example 2** <br>
Show that scalar 7 is an eigenvalue of A in example 1, and find the corresponding eigenvectors. <br>
**Calculation** <br>
The scalar 7 is an eigenvector of A if and only if equation A$\bullet$X = 7X has a nontrival solution. <br>
This equation is equal to Ax - 7x = 0, or (A-7I)x =0 <br>
To solve this equation, from the matrix
A - 7I =  $\left[ \begin{array}{ccc} 1 & 6\\ 5 & 2 \end{array} \right]$ $-$ $\left[ \begin{array}{ccc} 7 & 0\\ 0 & 7 \end{array} \right]$ =  $\left[ \begin{array}{ccc} -6 & 6\\ 5 & -5 \end{array} \right]$
The columns of A-7I are obviously linearly dependent, so has nontrivial solution. Thus 7 is an eigenvalue of A. To find the corresponding eigenvectors, use row operations. 

$\left[ \begin{array}{ccc} -6 & 6 & 0\\ 5 & -5 & 0\end{array} \right]$ $\sim$ $\left[ \begin{array}{ccc} 1 & -1 & 0\\ 0 & 0 & 0 \end{array} \right]$

(If you want to know the code which you can use for row reduction, have a look at the cell below.)
The general solution has the form x<sub>2</sub> $\left[ \begin{array}{ccc} 1\\ 1 \end{array} \right]$. Each vector of this form with x<sub>2</sub> $\neq$ 0 is an eigenvector corresponding to $\lambda$ = 7.

    


In [4]:
# the code for row reduction
from sympy import *
A = np.array([[-6, 6, 0],
            [5, -5, 0]])

reduced_A = Matrix(A).rref()
print(reduced_A)

(Matrix([
[1, -1, 0],
[0,  0, 0]]), (0,))


#### 2.2 The calculation of eigenvalues and eigenvectoren in python

The function **numpy.linalg.eig** computes eigenvalues and eigenvectors of a square matrix A. you have to import it before you can use it.

In [85]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as la

Let's consider a simple example with a diagonal matrix:

In [110]:
A = np.array([[3,-2],[1,0]])
print(A)

[[ 3 -2]
 [ 1  0]]


The function **la.eig** returns a tuple (eigvals,eigvecs) where eigvals is a 1D NumPy array of complex numbers giving the eigenvalues of A, and eigvecs is a 2D NumPy array with the corresponding eigenvectors in the columns:

In [111]:
results = la.eig(A)
print(results)


(array([ 2.,  1.]), array([[ 0.89442719,  0.70710678],
       [ 0.4472136 ,  0.70710678]]))


With the following code you get the eigenvalues and eigenvectors separately.

In [112]:
print("The eigenvalues of A are", results[0])
print("The corresponding eigenvectors are", results[1])

The eigenvalues of A are [ 2.  1.]
The corresponding eigenvectors are [[ 0.89442719  0.70710678]
 [ 0.4472136   0.70710678]]


It is also possible to split the eigenvectors and eigenvalues immediately

In [113]:
eigenvalues, eigenvectors = la.eig(A)
print(eigenvalues)
print(eigenvectors)

[ 2.  1.]
[[ 0.89442719  0.70710678]
 [ 0.4472136   0.70710678]]




#### 2.3 Excercises 


**2.3.1** Compute the eigenvalues and the corresponding eigenvectors of the given matrix $A = \left[ \begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{array} \right]$.

In [108]:
##mogelijk nog een filmpje met extra uitleg hier toevoegen

<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-bottom:-20px"></div>

### 3. Transformations

<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-top:5px;"></div>

#### 3.1 Definition

A transformation T from $\mathbb{R}$<sup>n</sup> to $\mathbb{R}$<sup>m</sup> is a rule that assigns to each vector x in $\mathbb{R}$<sup>n</sup> a vector T(x) in <br> $\mathbb{R}$<sup>m</sup>. The set $\mathbb{R}$<sup>n</sup> is called the domain of T, and $\mathbb{R}$<sup>m</sup> is called the codomain of T. <br> The notation T: $\mathbb{R}$<sup>n</sup> $ \longrightarrow$  $\mathbb{R}$<sup>m</sup> indicates that the domain of T is $\mathbb{R}$<sup>n</sup> and the codomain is $\mathbb{R}$<sup>m</sup>. For x in $\mathbb{R}$<sup>n</sup>, the vector T(x) is called the image of x (under the action of T). The set of all images T(x) is called the range of T. <br>
<img src="picture_transformation.PNG" /> <br>
So, with a transformation you have a matrix A that you multiply by a vector x which lead to a transformation of the vector x in b. <br>
<img src="picture_transformation2.PNG" /> <br>

#### 3.2 Examples
To get a transformation more gain insight we will give same examples.
#### hier nog wat toevoegen. overleggen in vergadering


#### 3.3 Excercises 

**3.3.1** Calculate the transformation.....

In [ ]:
#code.....

**3.3.2** nog maken

In [ ]:
#code.....

In [89]:
#aan het uitproberen
A = np.array([[0, 1],
                  [0,1]])
print(A)

import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(x=[1, 2, 3, 4], y=[0, 2, 3, 5], fill='tozeroy',
                    mode='none' # override default markers+lines
                    ))
fig.add_trace(go.Scatter(x=[1, 2, 3, 4], y=[3, 5, 1, 7], fill='tonexty',
                    mode= 'none'))

fig.show()
                    

[[0 1]
 [0 1]]


AttributeError: module 'plotly.graph_objs' has no attribute 'FigureWidget'

<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-bottom:-20px"></div>

###  4. Inner product, length and orthogonality

<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-top:5px;"></div>


### Inner product
#### 4.1.1 Definition
If $\mathbf{u}$ and $\mathbf{v}$ are vectors in $\mathbb{R}$<sup>n</sup> , then we regard $\mathbf{u}$ and $\mathbf{v}$ as *n x 1* matrices. The transpose $\mathbf{u}$<sup>*T*</sup> is a *1 x n* matrix, and the matrix product $\mathbf{u}$<sup>*T*</sup>$\mathbf{v}$ is a *1 x 1* matrix, which we write as a single real number (a scalar) without brackets. The number $\mathbf{u}$<sup>*T*</sup>$\mathbf{v}$ is called the **inner product** of $\mathbf{u}$ and $\mathbf{v}$, and often it is written as $\mathbf{u}\cdot\mathbf{v}$.

$$ \mathbf{u}= \left[ \begin{array}{c} u1 \\ u2 \\ \vdots \\ un \end{array} \right] \text{  and  } \mathbf{ v}= \left[ \begin{array}{c} v1 \\ v2 \\ \vdots \\ vn \end{array} \right]$$


then the inner product of u and v is <br>
$$\mathbf{u}\cdot\mathbf{v} = \mathbf{u}^T\mathbf{v} =  \left[ \begin{array}{c} u1 & u2 & \cdots & un \end{array} \right]  \left[ \begin{array}{c} v1 \\ v2 \\ \vdots \\ vn \end{array} \right] = u_1v_1+u_2v_2+\cdots+u_nv_n$$

#### 4.1.2 Examples
To calculate the inner product in Jupyter the following code can be used.<br>
Ordinary inner product for vectors: 
```python
A = np.array([1,2,3])
B = np.array([0,1,0])
np.inner(A, B)
```
A multidimensional example:
```python
a = np.arange(24).reshape((2,3,4))
b = np.arange(4)
np.inner(a, b)
```
### Lenght
#### 4.2.1 Definition
The length (or norm) of $\mathbf{v}$ is the nonnegative scalar $\parallel v \parallel$ defined by <br>
$$\| v \| = \sqrt{v \cdot v} = \sqrt{v_1^2+v_2^2+\cdots+vn^2} \text{ and } \parallel v \parallel^2$= $v \cdot v$$

#### 4.2.2 Examples
The magnitude of a vector can be calculate as follows.
```python
x = np.array([1,2,3,4,5])
np.linalg.norm(x)
#or   
np.sqrt(x.dot(x))
```

### Orthogonality
#### 4.3.1 Definition
**Orthogonal vectors** <br>
Two vectors $\mathbf{A}$ and $\mathbf{B}$ in $\mathbb{R}$<sup>n</sup> are orthogonal (to each other) if $\mathbf{A}\cdot\mathbf{B}$ =0
meaning that two vector are perpendicular to which another.

<img src="orthogonal.PNG" /> <br>

**Orthogonal** set<br>
A set of vectors {$\mathbf{u_1}, ... , \mathbf{u_p}$} in $\mathbb{R}$<sup>n</sup> is said to be an **orthogonal set** if each pair of distinct vectors from the set is orthogonal: $\mathbf{u_i} \cdot \mathbf{v_j}$ = 0 whenever i≠j .

**Example** <br>
Show that {$\mathbf{u_1},\mathbf{u_2},\mathbf{u_3}$} is an orthogonal set, where

$$\mathbf{u_1}=\left[ \begin{array}{c} 3 \\ 1 \\ \ 1  \end{array} \right], \mathbf{u_2}=\left[ \begin{array}{c} -1 \\ 2 \\ \ 1  \end{array} \right], \mathbf{u_3}=\left[ \begin{array}{c} -1/2 \\ -2 \\ \ 7/2  \end{array} \right]$$

**Solution** <br>
Consider the three possible pairs of distinct vectors, namely, {$\mathbf{u_1},\mathbf{u_2}$}, {$\mathbf{u_1},\mathbf{u_3}$} and {$\mathbf{u_2},\mathbf{u_3}$}

$\mathbf{u_1},\mathbf{u_2}= 3(-1)+1(2)+1(1)$ <br>
$\mathbf{u_1},\mathbf{u_3}=3(-1/2)+1(-2)+1(7/2)$ <br>
$\mathbf{u_2},\mathbf{u_3}=3(-1/2)+2(2)+1(7/2)$ <br>

<img src="orthogonal_set1.PNG" /> <br>

<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-bottom:-20px"></div>

###  5.Covariance and Mean

<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-top:5px;"></div>

#### 5.1 Definition
Before the principal component analysis can be made the following concept need to be explain. The figure below is a scatter plot of a two-dimensional data and it's matrix  (weight and height of N college students). The $X_j$ denote is the **oberservation vector** in $\mathbb{R}$<sup>2</sup> that lists the weight and height of the *j* th student.
<img src="two-dimensional_scatter_plot.PNG" /> <img src="observation_vector.PNG" /> <br>

The sample **mean, M**, of the observation vectors $X_1,\cdots, X_N$ is given by <br>
$$M=\frac{1}{n}(X_1+ \cdots+ X_n)$$

For the data in the scatter plot above, the sample mean is the point in the “center” of the scatter plot.
For $k =1, \cdots,N$  let <br>
$$\hat{X_k}=X_k-M$$


The columns of the *p x N* matrix <br>
$$ \mathbf{B}= \left[ \begin{array}{c} \hat{X_1} & \hat{X_2} & \cdots & \hat{X_n} \end{array} \right]$$

have a zero sample mean, and B is said to be in mean-deviation form. When the sample mean is subtracted from the data in the Figure above, the resulting scatter plot has the form in the figure below.
<img src="scatter_plot_center.PNG" /> <br>

The (sample) covariance matrix is the *p x p* matrix S defined by <br>
$$S=\frac{1}{N-1}BB^T$$

#### 5.2 Example
Three measurements are made on each of four individuals in a random
sample from a population. The observation vectors are <br>
$$\mathbf{X_1}=\left[ \begin{array}{c} 1 \\ 2 \\  1  \end{array} \right], \mathbf{X_2}=\left[ \begin{array}{c} 4 \\ 2 \\  13  \end{array} \right], \mathbf{X_3}=\left[ \begin{array}{c} 7 \\ 8 \\  1  \end{array} \right],
\mathbf{X_4}=\left[ \begin{array}{c} 8 \\ 4 \\  5  \end{array} \right]$$ <br>
Compute the sample mean and the covariance matrix.
The sample mean is<br>
$$M=\frac{1}{4}\left( \begin{array}{c}\left[ \begin{array}{c} 1 \\ 2 \\  1  \end{array} \right] + \left[ \begin{array}{c} 4 \\ 2 \\  13  \end{array} \right] + \left[ \begin{array}{c} 7 \\ 8 \\  1  \end{array} \right] +
\left[ \begin{array}{c} 8 \\ 4 \\  5  \end{array} \right] \end{array} \right) = \frac{1}{4} \left[ \begin{array}{c} 20 \\ 16 \\  20  \end{array} \right] = \left[ \begin{array}{c} 5 \\ 4 \\  5  \end{array} \right]$$ <br>

Subtract the sample mean from $X_1, \cdots, X_4$ to obtain <br>
$$\mathbf{X_1}=\left[ \begin{array}{c} -4 \\ -2 \\  -4  \end{array} \right], \mathbf{X_2}=\left[ \begin{array}{c} -1 \\ -2 \\  8  \end{array} \right], \mathbf{X_3}=\left[ \begin{array}{c} 2 \\ 4 \\  -4  \end{array} \right],
\mathbf{X_4}=\left[ \begin{array}{c} 3 \\ 0 \\  0  \end{array} \right]$$ <br>
and <br>
$$ B = \left[ \begin{array}{cccc}  -4 & -1 & 2 & 3\\ -2 & -2 & 4 & 0 \\ -4 & 8 & -4 & 0  \end{array} \right]$$ <br>

The sample covariance matrix is <br>
$$ S = \frac{1}{3}  \left[ \begin{array}{ccc}  -4 & -1 & 2 & 3\\ -2 & -2 & 4 & 0 \\ -4 & 8 & -4 & 0  \end{array} \right] \left[ \begin{array}{cccc}  -4 & -2 & 4\\ -1 & -2 & 8 \\ 2 & 4 & -4\\3 & 0 & 0  \end{array} \right] \\
=\frac{1}{3}  \left[ \begin{array}{ccc}  30 & 18 & 0\\ 18 & 24 & -24\\ 0 & -24 & 96  \end{array} \right] = \left[ \begin{array}{ccc}  10 & 6 & 0\\ 6 & 8 & -8\\ 0 & -8 & 32  \end{array} \right] $$

For $j = 1, \cdots,p$, the diagonal entry $s_{jj}$ in $S$ is called the **variance** of $x_j$ .
The variance of $x_j$ measures the spread of the values of $x_j$ . In the Example , the variance of $x_1$ is 10 and the variance of $x_3$ is 32. The fact that 32 is more than 10 indicates that the set of third entries in the response vectors contains a wider spread of values than the set of first entries.<br> 

The **total variance** of the data is the sum of the variances on the diagonal of $S$. In general, the sum of the diagonal entries of a square matrix $S$ is called the **trace** of the
matrix, written tr($S$) Thus <br>
$$\text{{total variance}} = tr(\text{$S$})$$

The entry $s_{ij}$ in $S$ for $i \neq j$ is called the **covariance** ($cov$) of $x_i$ and $x_j$ . Observe that
in the Example, the covariance between $x_1$ and $x_3$ is 0 because the (1, 3)-entry in $S$ is 0. Statisticians say that x1 and x3 are **uncorrelated**.
If the variables are correlated in some way, then their covariance will be nonzero. In fact, if $cov_{i j}$ > 0, then  Y tends to increase as  X increases, and if $cov_{i j}$ < 0, then Y tends to decrease as X increases. However, the amount of correlation cannot be determined with covariance instead with correlationcoefficient.

#### 5.3 code
The function cov from numpy computes the Covaince Matrix.
```python
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print("matrix=",A)
# calculate the mean of each column
M = mean(A.T, axis=1)
print("Mean=",M)
# center columns by subtracting column means
C = A - M
print("C=",C)
# calculate covariance matrix of centered matrix
V = cov(C.T)
print("covariance matrix=",V)
```


<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-bottom:-20px"></div>

### Excercises 

<div class="alert alert-info" role="alert" style="height:10px;padding:0px;margin-top:5px;"></div>


**1.1** Calculate the covariance matrix of two given arrays. 
Sample Output:
Original array1:
[0 1 2]
Original array1:
[2 1 0]

**1.2** something with a graph...